function out=importfilemc5(fileToRead1,HEADERLINES)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
%  Auto-generated by MATLAB on 07-May-2010 04:27:29
DELIMITER = ' ';
% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);
out=newData1.data;
% Create new variables in the base workspace from those fields.

